#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#    Aug 05, 2019 10:05:06 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import login_gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    login_gui_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    login_gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font11 = "-family {Open Sans} -size 10 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family {Open Sans} -size 11 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font13 = "-family {Open Sans} -size 14 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Open Sans} -size 20 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("360x349+786+200")
        top.title("Login")
        top.configure(background="#444")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.login_frame = tk.Frame(top)
        self.login_frame.place(relx=0.0, rely=-0.029, relheight=1.046
                , relwidth=1.014)
        self.login_frame.configure(relief='groove')
        self.login_frame.configure(borderwidth="1")
        self.login_frame.configure(relief="groove")
        self.login_frame.configure(background="#444")
        self.login_frame.configure(highlightbackground="#d9d9d9")
        self.login_frame.configure(highlightcolor="black")
        self.login_frame.configure(width=365)

        self.welcome_label = tk.Label(self.login_frame)
        self.welcome_label.place(relx=0.0, rely=0.11, height=81, width=354)
        self.welcome_label.configure(activebackground="#f9f9f9")
        self.welcome_label.configure(activeforeground="black")
        self.welcome_label.configure(background="#444")
        self.welcome_label.configure(disabledforeground="#a3a3a3")
        self.welcome_label.configure(font=font9)
        self.welcome_label.configure(foreground="white")
        self.welcome_label.configure(highlightbackground="#d9d9d9")
        self.welcome_label.configure(highlightcolor="black")
        self.welcome_label.configure(text='''Welcome to the chat!''')

        self.username_entry = tk.Entry(self.login_frame)
        self.username_entry.place(relx=0.205, rely=0.411, height=30
                , relwidth=0.559)
        self.username_entry.configure(background="white")
        self.username_entry.configure(disabledforeground="#a3a3a3")
        self.username_entry.configure(font="TkFixedFont")
        self.username_entry.configure(foreground="#000000")
        self.username_entry.configure(highlightbackground="#d9d9d9")
        self.username_entry.configure(highlightcolor="black")
        self.username_entry.configure(insertbackground="black")
        self.username_entry.configure(selectbackground="#c4c4c4")
        self.username_entry.configure(selectforeground="black")

        self.btn_login = tk.Button(self.login_frame)
        self.btn_login.place(relx=0.205, rely=0.575, height=34, width=204)
        self.btn_login.configure(activebackground="#31e0c9")
        self.btn_login.configure(activeforeground="#000000")
        self.btn_login.configure(background="#31e0c9")
        self.btn_login.configure(disabledforeground="#a3a3a3")
        self.btn_login.configure(font=font12)
        self.btn_login.configure(foreground="#000000")
        self.btn_login.configure(highlightbackground="#d9d9d9")
        self.btn_login.configure(highlightcolor="black")
        self.btn_login.configure(pady="0")
        self.btn_login.configure(text='''Login''')
        self.btn_login.configure(width=197)

        self.Label2 = tk.Label(self.login_frame)
        self.Label2.place(relx=0.205, rely=0.301, height=31, width=194)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#444")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font13)
        self.Label2.configure(foreground="white")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Enter username''')

        self.Canvas1 = tk.Canvas(self.login_frame)
        self.Canvas1.place(relx=0.055, rely=0.795, relheight=0.003
                , relwidth=0.83)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=303)

        self.info_msg_label = tk.Label(self.login_frame)
        self.info_msg_label.place(relx=0.068, rely=0.822, height=51, width=294)
        self.info_msg_label.configure(activebackground="#f9f9f9")
        self.info_msg_label.configure(activeforeground="black")
        self.info_msg_label.configure(background="#444")
        self.info_msg_label.configure(borderwidth="0")
        self.info_msg_label.configure(disabledforeground="#a3a3a3")
        self.info_msg_label.configure(font=font11)
        self.info_msg_label.configure(foreground="white")
        self.info_msg_label.configure(highlightbackground="#d9d9d9")
        self.info_msg_label.configure(highlightcolor="black")
        self.info_msg_label.configure(justify='left')

if __name__ == '__main__':
    vp_start_gui()





